### PR TITLE
Issue 720 test User.Teams

### PR DESCRIPTION
**Pull request by rjourde**

### CODE REVIEW

**Comment by santiaago** [comment]
It is good.

I would like a test array with

* a user that does not have teams
* a user that has teams
* a user that has teams but one/or more of them do not exist.

~~~go
tests := []struct {
		title string
		teams []testTeam
	}
~~~

**Comment by rjourde** [comment]
How is it possible to test this?
* a user that has teams but one/or more of them do not exist.

**Comment by santiaago** [comment]
the user that a list of `teamIds` so you can alter that list.

**Comment by rjourde** [comment]
ok I see but is it right to do this because I rely on team.Join to test user.Teams and it is the job of team.Join to manage the list of teamIds.

**Comment by santiaago** [comment]
yes, it is only to test the errors, so use it on a user that you do not use to test elsewhere

**Comment by santiaago** [comment]
or  if you don't save the user after you should be alright

**Comment by rjourde** [comment]
user.Teams does not return an error. A slice of team pointers is returned.

**Comment by santiaago** [comment]
you can test that the size of the slice does not match the size of the teamIds

**Comment by rjourde** [comment]
Ok.

**Comment by santiaago** [comment]
:+1:

**Pull request merged**
