### PR TITLE
Issue 715 test User.UserKeysByIds

### PR DESCRIPTION
**Pull request by rjourde**

### CODE REVIEW

**Comment by santiaago** [comment]
Not sure if this works as the datastore does not have any data?

**Comment by rjourde** [comment]
You can still create a key for a given entity.

**Comment by santiaago** [comment]
This test is wrong as the `keys := UserKeysByIds(c, test.userIDs)` returns an array of 0 keys. Because it does not find it in the datastore. It should fail, if it does not fail then the test needs to be changed to fail. Then fix the issue by storing the users before running the test.

Run the test alone with `goapp test -v -run=^TestUserKeysByIds$`

**Comment by rjourde** [comment]
I executed the test and I have got
` --- PASS: TestUserKeysByIds (4.90s)`
 `user_test.go:221: can get user keys by IDs`
 `user_test.go:227: key = /User,25`
 `user_test.go:227: key = /User,666`
 `user_test.go:227: key = /User,2042`

So a key is generated even if an entity has not been stored.

**Comment by santiaago** [comment]
ok I understand now.

Some comments: 

* This test does not need a `test.err`
* you should not test `if test.err == "" && keys != nil {` as the keys can never be `nil`

**Comment by rjourde** [comment]
I agree

**Comment by santiaago** [comment]
:+1:

**Pull request merged**
