### PR TITLE
Issue 675 Join user to tournaments at first predict

### PR DESCRIPTION
**Pull request by rjourde**

### CODE REVIEW

**Comment by santiaago** [comment]
how to test this manually?

**Comment by rjourde** [comment]
To test this I had to tweak the creation of world cup tournament to have good start and end dates. Then I could bet on a match and then checked that user has been well added as participamt.

**Comment by santiaago** [comment]
thanks!, I will test that!

**Comment by rjourde** [comment]
did you find time to test this?

**Pull request merged**
