### PR TITLE
Issue 728 Test CreateTeam

### PR DESCRIPTION
**Pull request by santiaago**

### CODE REVIEW

**Comment by santiaago** [comment]
Same as `TestCreateUser(t *testing.T) {` should we test error case there too?

**Comment by rjourde** [comment]
Yes we should.

**Comment by santiaago** [comment]
do you have an example? I will do both in this PR

**Comment by rjourde** [comment]
Look at the TestFindUser. There is an example of how to test error case.

**Comment by santiaago** [comment]
:+1:

**Comment by santiaago** [comment]
CreateTeam cannot fail on creation aside from an error in the datastore on `AllocateIDs` or on `datastore.put`. If you want that test you should also do the same for `CreateUser`.

**Comment by rjourde** [comment]
I can be dificult to trigger an error during `AllocateIDs` or `datastore.put`

**Comment by santiaago** [comment]
happy with this test?

**Comment by rjourde** [comment]
Yes I'm happy

**Pull request merged**
